# .github/workflows/build.yml
name: 编译 Windows x64 资源包 (标签触发)

on:
  push:
    tags:
      - 'v*'

jobs:
  compile-windows-x64:
    name: 编译 Windows x64 - Python ${{ matrix.python-version }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        # 确认版本清单中存在的稳定版本（如3.10.11）
        python-version: ["3.10.11"]  # 精确到补丁版，提升匹配成功率
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 计算产物名称
        id: artifact_name
        run: |
          $py_ver = "${{ matrix.python-version }}".Replace(".", "")
          $artifact_name = "sites.cp$py_ver-win_amd64.pyd"
          echo "ARTIFACT_NAME=$artifact_name" >> $env:GITHUB_ENV

      - name: 设置 Python（修正架构参数：x64 而非 amd64）
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64  # Windows 平台正确架构标识

      - name: 安装编译依赖
        run: |
          choco install -y mingw --version=11.2.0
          echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8
          python -m pip install --upgrade pip setuptools wheel cython

      - name: 编译扩展模块（需替换为真实命令）
        run: |
          mkdir -p build/app/helper
          # 示例：若项目用 setup.py 构建
          # python setup.py build_ext --inplace --compiler=mingw32
          echo "模拟编译产物: ${{ env.ARTIFACT_NAME }}" > build/app/helper/${{ env.ARTIFACT_NAME }}

      - name: 验证产物
        run: |
          if (-not (Test-Path "build/app/helper/${{ env.ARTIFACT_NAME }}")) {
            Write-Error "产物缺失: ${{ env.ARTIFACT_NAME }}"
            exit 1
          }

      - name: 打包资源
        run: |
          mkdir -p artifacts/app/helper
          cp build/app/helper/${{ env.ARTIFACT_NAME }} artifacts/app/helper/
          cp LICENSE package.json package.v2.json artifacts/ -ErrorAction SilentlyContinue
          echo "资源版本：${{ github.ref_name }}" > artifacts/VERSION

      - name: 上传产物
        uses: actions/upload-artifact@v4
        with:
          name: Windows-x64-py${{ matrix.python-version }}-${{ github.ref_name }}
          path: artifacts/

  create-release:
    needs: compile-windows-x64
    runs-on: ubuntu-latest
    steps:
      - name: 下载产物
        uses: actions/download-artifact@v4
        with:
          path: all-artifacts

      - name: 创建 Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            all-artifacts/**/*.pyd
            all-artifacts/**/LICENSE
            all-artifacts/**/package*.json
            all-artifacts/**/VERSION
